"""
    Hilfsmittel-API

    Der GKV-Spitzenverbund führt ein Register über alle Hilfsmittel, die der Leistungspflicht der Kassen unterliegen. Struktur: Produktgruppe -> Anwendungsort -> Untergruppe -> Produktart -> Produkt  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.hilfsmittel.model.nachweisschema_nachweisschema_kategorie_zuweisungen_inner import (
    NachweisschemaNachweisschemaKategorieZuweisungenInner,
)

from deutschland import hilfsmittel


class TestNachweisschemaNachweisschemaKategorieZuweisungenInner(unittest.TestCase):
    """NachweisschemaNachweisschemaKategorieZuweisungenInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNachweisschemaNachweisschemaKategorieZuweisungenInner(self):
        """Test NachweisschemaNachweisschemaKategorieZuweisungenInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NachweisschemaNachweisschemaKategorieZuweisungenInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
