"""
    Hilfsmittel-API

    Der GKV-Spitzenverbund führt ein Register über alle Hilfsmittel, die der Leistungspflicht der Kassen unterliegen. Struktur: Produktgruppe -> Anwendungsort -> Untergruppe -> Produktart -> Produkt  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.hilfsmittel.model.detail_produkt_all_of_kontruktionsmerkmale import (
    DetailProduktAllOfKontruktionsmerkmale,
)

from deutschland import hilfsmittel


class TestDetailProduktAllOfKontruktionsmerkmale(unittest.TestCase):
    """DetailProduktAllOfKontruktionsmerkmale unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetailProduktAllOfKontruktionsmerkmale(self):
        """Test DetailProduktAllOfKontruktionsmerkmale"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetailProduktAllOfKontruktionsmerkmale()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
