"""
    Hilfsmittel-API

    Der GKV-Spitzenverbund führt ein Register über alle Hilfsmittel, die der Leistungspflicht der Kassen unterliegen. Struktur: Produktgruppe -> Anwendungsort -> Untergruppe -> Produktart -> Produkt  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.hilfsmittel.model.nachweisschema_nachweis_abschnitt_anforderungen_inner import (
    NachweisschemaNachweisAbschnittAnforderungenInner,
)
from deutschland.hilfsmittel.model.nachweisschema_nachweisschema_kategorie_zuweisungen_inner import (
    NachweisschemaNachweisschemaKategorieZuweisungenInner,
)

from deutschland import hilfsmittel

globals()[
    "NachweisschemaNachweisAbschnittAnforderungenInner"
] = NachweisschemaNachweisAbschnittAnforderungenInner
globals()[
    "NachweisschemaNachweisschemaKategorieZuweisungenInner"
] = NachweisschemaNachweisschemaKategorieZuweisungenInner
from deutschland.hilfsmittel.model.nachweisschema import Nachweisschema


class TestNachweisschema(unittest.TestCase):
    """Nachweisschema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNachweisschema(self):
        """Test Nachweisschema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Nachweisschema()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
