"""
    Hilfsmittel-API

    Der GKV-Spitzenverbund führt ein Register über alle Hilfsmittel, die der Leistungspflicht der Kassen unterliegen. Struktur: Produktgruppe -> Anwendungsort -> Untergruppe -> Produktart -> Produkt  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.hilfsmittel.model.produktgruppe import Produktgruppe

from deutschland import hilfsmittel


class TestProduktgruppe(unittest.TestCase):
    """Produktgruppe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProduktgruppe(self):
        """Test Produktgruppe"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Produktgruppe()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
